/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCustomizeRouteImport } from './routes/api/customize'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomizeRoute = ApiCustomizeRouteImport.update({
  id: '/api/customize',
  path: '/api/customize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/customize': typeof ApiCustomizeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/customize': typeof ApiCustomizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/customize': typeof ApiCustomizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/checkout' | '/api/customize'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/checkout' | '/api/customize'
  id: '__root__' | '/' | '/api/checkout' | '/api/customize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiCustomizeRoute: typeof ApiCustomizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customize': {
      id: '/api/customize'
      path: '/api/customize'
      fullPath: '/api/customize'
      preLoaderRoute: typeof ApiCustomizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiCustomizeRoute: ApiCustomizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
